const sidebars = {
  tbbSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "generated-index",
        title: "Getting Started",
        description:
          "This section guides you through the full setup and flow of a new AEM project.",
        slug: "/getting-started",
      },
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Components",
      link: {
        type: "generated-index",
        title: "Components Overview",
        description: "Explore the AEM components used in our projects.",
        slug: "/components",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "components",
        },
      ],
    },
    {
      type: "category",
      label: "Development Process",
      link: {
        type: "generated-index",
        title: "Development Process",
        description:
          "Processes that ensure consistent quality across our development workflow.",
        slug: "/development",
      },
      items: [{ type: "autogenerated", dirName: "development" }],
    },
    {
      type: "category",
      label: "Performance",
      link: {
        type: "generated-index",
        title: "Performance Guidelines",
        description: "Lighthouse, RUM, and optimization tips for TBB projects.",
        slug: "/performance",
      },
      items: [{ type: "autogenerated", dirName: "performance" }],
    },
    {
      type: "category",
      label: "Page Settings",
      link: {
        type: "generated-index",
        title: "Page Settings",
        description: "Learn how to configure AEM page properties and behavior.",
        slug: "/page-settings",
      },
      items: [{ type: "autogenerated", dirName: "page-settings" }],
    },
  ],
};

export default sidebars;
