name: Trigger Netlify Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Request Netlify Build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Deploy
        uses: nwtgck/actions-netlify@v3
        with:
          publish: false

          deploy-hook-url: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}